# A basic script template used by Alembic when autogenerating
# migration files. Kept minimal to support simple revisions.
"""track bin size

Revision ID: 006006cc2134
Revises: ec957bbedc43
Create Date: 2026-02-22 21:05:24.857260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '006006cc2134'
down_revision: Union[str, None] = 'ec957bbedc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('bins', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.drop_column('bins', 'size')
    # ### end Alembic commands ###
