# A basic script template used by Alembic when autogenerating
# migration files. Kept minimal to support simple revisions.
"""remove description from parts

Revision ID: ec957bbedc43
Revises: 137f476c8392
Create Date: 2026-02-22 10:52:46.545744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec957bbedc43'
down_revision: Union[str, None] = '137f476c8392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
