# A basic script template used by Alembic when autogenerating
# migration files. Kept minimal to support simple revisions.
"""remove name from bins

Revision ID: f586964f213f
Revises: dbb2b229930a
Create Date: 2026-01-28 21:42:13.264669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f586964f213f'
down_revision: Union[str, None] = 'dbb2b229930a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bins', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('name', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
